version: '3.8'

services:
  library_app:
    build: .
    container_name: python_library_app
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=library
    depends_on:
      - postgres_db
    # Оскільки у нас CLI-додаток, ці два параметри дозволяють йому тримати консоль відкритою
    stdin_open: true
    tty: true

  postgres_db:
    image: postgres:15-alpine
    container_name: library_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: